### Pandas DataFrame

#### Create DataFrame

In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame({'Name':['Anna','Ben'],
                    'Lemonade':[2,3]})

In [4]:
data

   Name  Lemonade
0  Anna         2
1   Ben         3

In [5]:
s1 = pd.Series(data=[1,2,3,4])

In [6]:
s2 = pd.Series(data=[10,20,30,40])

In [7]:
data2 = pd.DataFrame({'C1':s1,'C2':s2})

In [8]:
data2

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40

In [24]:
data2.to_csv('lemonade.csv')

In [25]:
df = pd.read_csv('lemonade.csv')

In [26]:
df

   Unnamed: 0  C1  C2
0           0   1  10
1           1   2  20
2           2   3  30
3           3   4  40

In [30]:
import numpy as np

In [31]:
dictt = {'x':[1,2,3],'y':np.array([10,20,30]),'z':50}

In [32]:
pd.DataFrame(dictt)

   x   y   z
0  1  10  50
1  2  20  50
2  3  30  50

In [33]:
listt = [[1,2,3,4],[10,20,30,40],[100,200,300,400]]

In [35]:
pd.DataFrame(listt,columns=['x','y','z','a'])

     x    y    z    a
0    1    2    3    4
1   10   20   30   40
2  100  200  300  400

In [36]:
narr = np.array([[1,2,100],[2,4,100],[3,6,100]])

In [37]:
pd.DataFrame(narr,columns=['x','y','z'])

   x  y    z
0  1  2  100
1  2  4  100
2  3  6  100

#### Attributes

In [9]:
data2.shape

(4, 2)

In [10]:
data2.columns

Index(['C1', 'C2'], dtype='object')

In [23]:
data2.dtypes

C1    int64
C2    int64
dtype: object

#### Access Data

In [13]:
data2.loc[1,'C1']

2

In [14]:
data2.loc[3,'C2']

40

In [15]:
data2.iloc[1,0]

2

In [18]:
data2.iloc[1,1]

20

#### Methods

In [19]:
data2.head()

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40

In [20]:
data2.count()

C1    4
C2    4
dtype: int64

In [21]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      4 non-null      int64
 1   C2      4 non-null      int64
dtypes: int64(2)
memory usage: 196.0 bytes

In [22]:
data2.describe()

             C1         C2
count  4.000000   4.000000
mean   2.500000  25.000000
std    1.290994  12.909944
min    1.000000  10.000000
25%    1.750000  17.500000
50%    2.500000  25.000000
75%    3.250000  32.500000
max    4.000000  40.000000

In [39]:
data2.sort_values(by='C2')

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40

#### Filtering

In [41]:
data2[data2['C1'] >= 2]

   C1  C2
1   2  20
2   3  30
3   4  40

#### Adding,updating,deleting

In [47]:
data2['Tips'] = [100,200,300,400]

In [43]:
data2

   C1  C2  Tips
0   1  10   100
1   2  20   200
2   3  30   300
3   4  40   400

#### delete

In [45]:
del data2['Tips']

In [48]:
data2

   C1  C2  Tips
0   1  10   100
1   2  20   200
2   3  30   300
3   4  40   400

In [50]:
data2.drop(columns=['Tips'])

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40

In [52]:
data2.loc[data2['C1']==2] = 10

In [53]:
data2

   C1  C2  Tips
0   1  10   100
1  10  10    10
2   3  30   300
3   4  40   400

In [54]:
data2.rename(columns={'C1':'Column1'})

   Column1  C2  Tips
0        1  10   100
1       10  10    10
2        3  30   300
3        4  40   400

#### Indexing & Selection

In [55]:
data2.set_index('Column1',inplace=True)

KeyError: "None of ['Column1'] are in the columns"